-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "See 8"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlaceItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "finish editing component"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Motherboard",
    [2] = game:GetService("Players").LocalPlayer.PcItems.A15
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "PowerSuply",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Silver 500w")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Cpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("4 1500")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Ram",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Ram 8Gb")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Memory",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("256Gb")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Gpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("1080X RGB")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Fan",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("Vortex RGB")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "Water",
    [2] = game:GetService("Players").LocalPlayer.PcItems:FindFirstChild("LC X2 RGB")
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "17K Coins"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.Save:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
wait(0.5)
local args = {
    [1] = "17K Coins"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.Sell:FireServer(unpack(args))
